FROM n8nio/n8n:latest
USER root

# Install Python and pip
RUN apk add --no-cache python3 py3-pip

# Copy and install python requirements
COPY scripts/requirements.txt /tmp/requirements.txt
RUN pip3 install --break-system-packages -r /tmp/requirements.txt

USER node
